COMMONINFO:
  regional_object: gcm-test
NATS:
  host: 192.168.9.208
  port: 4222
  cache_ttl: 3600
  subscriptions:
    some: somesubscription
  enriching_queries:
    get_geoip_info: object.geoip-request.test
    get_sensor_info: object.sensor-info-request.test
KAFKA:
  host: 192.168.9.73
  port: 30932
  cache_ttl: 3600
  group_id: "gcm-group" # для ГЦМ оставляем пустым
  topics:
    alerts: object.topicalerttype.test
    soar-alerts: object.topicsoaralertstype.test
  sasl_mechanism: SCRAM-SHA-512 # PLAIN, SCRAM-SHA-256, SCRAM-SHA-512
  ssl_username: siem2
  ssl_ca_file: "/secrets/truststore.jks" # ca.crt или truststore.jks # ca.crt или truststore.jks (определяет набор корневых центров сертификации которые клиенты используют при проверке сертификатов сервера)
  ssl_cert_file: "/secrets/ca.crt" # client.crt открытый сертификат клиента, параметр и только для тестов
  ssl_key_file: "" # client.key закрытый ключ для сертификата клиента, параметр и только для тестов
  # если ssl_ca_file, ssl_cert_file и ssl_key_file пустые то будут выполнятся поппытки соединения с сервером
  # kafka без использования протокола TLS
  ssl_server_name: "kafka-cluster-kafka-bootstrap" # имя сервера kafka указанное в сертификате клиента
DATABASESTORAGE:
  host: 192.168.9.208
  port: 9200
  user: placeholder-docbasedb-bizone
  namedb: ""
  storage_name_db:
    alerts: module_placeholderdb_bizone_alerts.test
    soar-alerts: module_placeholderdb_bizone_soar-alerts.test
DATABASEWRITELOG:
  host: 192.168.9.208
  port: 9200
  user: user-placeholder-docbasedb-bizone_log
  namedb: ""
  storage_name_db: db-placeholder_docbasedb-bizone_log
DEBUGSERVER:
  enable: true
  host: localhost
  port: 6565
